theme: jekyll-theme-minimal

title: David A. Nader
description: PhD Candidate in Computer Science [**ResearchGate**](https://www.researchgate.net/profile/David-Nader)

logo: /images/profile_nader.jpg
show_downloads: true
