source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'al_cookie', '= 1.0.0'
    gem 'al_folio_core', '= 1.0.11'
    gem 'al_folio_cv', '= 1.0.0'
    gem 'al_folio_distill', '= 1.0.2'
    gem 'al_folio_upgrade', '= 1.0.3'
    gem 'al_icons', '= 1.0.0'
    gem 'al_math', '= 1.0.1'
    gem 'classifier-reborn'
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-get-json'
    gem 'jekyll-imagemagick'
    gem 'jekyll-jupyter-notebook'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-tabs'
    gem 'jekyll-toc'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
end
group :other_plugins do
    gem 'css_parser'
    gem 'feedjira'
    gem 'httparty'
end
